/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author avim
 */
import com.mysql.jdbc.StringUtils;
import java.io.*;
import java.util.*;
import javax.swing.*;
import java.awt.*;
import static java.awt.Color.green;
import static java.awt.Color.white;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
 
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listerFrame = new javax.swing.JFrame();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listerText = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        supprimerFrame = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        msgErreur = new javax.swing.JDialog();
        jButton4 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        ajouterClient = new javax.swing.JFrame();
        labAge1 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        suivantAddCli1 = new javax.swing.JButton();
        txtId1 = new javax.swing.JTextField();
        txtNom1 = new javax.swing.JTextField();
        txtAge1 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        lab3 = new javax.swing.JLabel();
        labId1 = new javax.swing.JLabel();
        labNom1 = new javax.swing.JLabel();
        donateFrame = new javax.swing.JFrame();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        ajouterCommande = new javax.swing.JFrame();
        jSeparator4 = new javax.swing.JSeparator();
        lab4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        idCommande = new javax.swing.JTextField();
        idClient = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        cmd1 = new javax.swing.JButton();
        lbl1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        cmd2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        buttonDonate = new javax.swing.JMenuItem();
        About = new javax.swing.JMenuItem();

        jButton1.setText("Quitter");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        listerText.setColumns(20);
        listerText.setRows(5);
        listerText.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(listerText);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(java.awt.Color.red);
        jLabel6.setText("  Lister");

        javax.swing.GroupLayout listerFrameLayout = new javax.swing.GroupLayout(listerFrame.getContentPane());
        listerFrame.getContentPane().setLayout(listerFrameLayout);
        listerFrameLayout.setHorizontalGroup(
            listerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listerFrameLayout.createSequentialGroup()
                .addGroup(listerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(listerFrameLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(listerFrameLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listerFrameLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160))
        );
        listerFrameLayout.setVerticalGroup(
            listerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listerFrameLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel3.setForeground(java.awt.Color.red);
        jLabel3.setText("Supprimer un produit");

        jLabel4.setText("Entrer un identifiant :");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton2.setForeground(java.awt.Color.red);
        jButton2.setText("Quitter");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setForeground(java.awt.Color.blue);
        jButton3.setText("Suivant");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout supprimerFrameLayout = new javax.swing.GroupLayout(supprimerFrame.getContentPane());
        supprimerFrame.getContentPane().setLayout(supprimerFrameLayout);
        supprimerFrameLayout.setHorizontalGroup(
            supprimerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supprimerFrameLayout.createSequentialGroup()
                .addGroup(supprimerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(supprimerFrameLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, supprimerFrameLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(16, 16, 16)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        supprimerFrameLayout.setVerticalGroup(
            supprimerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(supprimerFrameLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(supprimerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(supprimerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jButton3))
                    .addGroup(supprimerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jButton4.setText("OK");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout msgErreurLayout = new javax.swing.GroupLayout(msgErreur.getContentPane());
        msgErreur.getContentPane().setLayout(msgErreurLayout);
        msgErreurLayout.setHorizontalGroup(
            msgErreurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, msgErreurLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField2)
                .addContainerGap())
            .addGroup(msgErreurLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jButton4)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        msgErreurLayout.setVerticalGroup(
            msgErreurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, msgErreurLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addGap(18, 18, 18))
        );

        labAge1.setText("Age :");

        jButton7.setForeground(java.awt.Color.red);
        jButton7.setText("Quitter");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(java.awt.Color.red);
        jLabel7.setText("Ajouter un client");

        suivantAddCli1.setForeground(java.awt.Color.blue);
        suivantAddCli1.setText("Suivant");
        suivantAddCli1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                suivantAddCli1MouseClicked(evt);
            }
        });

        txtId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId1ActionPerformed(evt);
            }
        });

        txtNom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNom1ActionPerformed(evt);
            }
        });

        txtAge1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAge1ActionPerformed(evt);
            }
        });

        lab3.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lab3.setForeground(java.awt.Color.blue);
        lab3.setText("Entrer les informations :");

        labId1.setText("Identifiant :");

        labNom1.setText("Nom :");

        javax.swing.GroupLayout ajouterClientLayout = new javax.swing.GroupLayout(ajouterClient.getContentPane());
        ajouterClient.getContentPane().setLayout(ajouterClientLayout);
        ajouterClientLayout.setHorizontalGroup(
            ajouterClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajouterClientLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(ajouterClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ajouterClientLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(ajouterClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labAge1)
                            .addComponent(labId1)
                            .addComponent(labNom1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(ajouterClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAge1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtId1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ajouterClientLayout.createSequentialGroup()
                                .addComponent(txtNom1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(suivantAddCli1))))
                    .addComponent(lab3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ajouterClientLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ajouterClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ajouterClientLayout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ajouterClientLayout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ajouterClientLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(162, 162, 162))))
        );
        ajouterClientLayout.setVerticalGroup(
            ajouterClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajouterClientLayout.createSequentialGroup()
                .addGroup(ajouterClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ajouterClientLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addGap(9, 9, 9)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ajouterClientLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(lab3)
                        .addGap(41, 41, 41)
                        .addGroup(ajouterClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ajouterClientLayout.createSequentialGroup()
                                .addComponent(labId1)
                                .addGap(29, 29, 29)
                                .addComponent(labNom1)
                                .addGap(24, 24, 24)
                                .addGroup(ajouterClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labAge1)
                                    .addComponent(txtAge1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(ajouterClientLayout.createSequentialGroup()
                                .addComponent(txtId1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(ajouterClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(suivantAddCli1))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addContainerGap())
        );

        jLabel9.setBackground(new java.awt.Color(255, 0, 0));
        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("MERCI DE DONNER POUR GESTION_PRODUIT");

        jLabel10.setText("Combien souhaitez vous donnez ?");

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setForeground(java.awt.Color.red);
        jButton5.setText("DONATE");

        javax.swing.GroupLayout donateFrameLayout = new javax.swing.GroupLayout(donateFrame.getContentPane());
        donateFrame.getContentPane().setLayout(donateFrameLayout);
        donateFrameLayout.setHorizontalGroup(
            donateFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donateFrameLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel10)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, donateFrameLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(donateFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, donateFrameLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, donateFrameLayout.createSequentialGroup()
                        .addGroup(donateFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSpinner1))
                        .addGap(124, 124, 124))))
        );
        donateFrameLayout.setVerticalGroup(
            donateFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(donateFrameLayout.createSequentialGroup()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lab4.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lab4.setForeground(java.awt.Color.blue);
        lab4.setText("Entrer les informations :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(java.awt.Color.red);
        jLabel11.setText("Ajouter une commande");

        jButton8.setForeground(java.awt.Color.red);
        jButton8.setText("Quitter");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        jLabel12.setText("DATE : ");

        jLabel13.setText("ID Client : ");

        jLabel14.setText("ID Commande : ");

        idClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idClientActionPerformed(evt);
            }
        });

        jButton6.setForeground(java.awt.Color.blue);
        jButton6.setText("Suivant");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ajouterCommandeLayout = new javax.swing.GroupLayout(ajouterCommande.getContentPane());
        ajouterCommande.getContentPane().setLayout(ajouterCommandeLayout);
        ajouterCommandeLayout.setHorizontalGroup(
            ajouterCommandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajouterCommandeLayout.createSequentialGroup()
                .addGroup(ajouterCommandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ajouterCommandeLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8))
                    .addGroup(ajouterCommandeLayout.createSequentialGroup()
                        .addGroup(ajouterCommandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ajouterCommandeLayout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ajouterCommandeLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(lab4))
                            .addGroup(ajouterCommandeLayout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jLabel11))
                            .addGroup(ajouterCommandeLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(ajouterCommandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12))
                                .addGap(32, 32, 32)
                                .addGroup(ajouterCommandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(idCommande)
                                    .addComponent(idClient, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                    .addComponent(date))))
                        .addGap(0, 91, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ajouterCommandeLayout.setVerticalGroup(
            ajouterCommandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajouterCommandeLayout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lab4)
                .addGap(30, 30, 30)
                .addGroup(ajouterCommandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(idCommande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(ajouterCommandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(idClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(ajouterCommandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(ajouterCommandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton6))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmd1.setForeground(java.awt.Color.red);
        cmd1.setText("Quitter");
        cmd1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmd1MouseClicked(evt);
            }
        });
        cmd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd1ActionPerformed(evt);
            }
        });

        lbl1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbl1.setText("Que voulez vous faire ?");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ajouter produit", "Lister produit", "Rechercher produit", "Supprimer produit", "Modifier produit", "Prix max", "Valeur stock", "Ajouter client", "Lister client", "Ajouter commande", "Rechercher commande" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        cmd2.setBackground(java.awt.Color.lightGray);
        cmd2.setForeground(java.awt.Color.blue);
        cmd2.setText("Suivant");
        cmd2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmd2MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("Bienvenue dans le programme\n");

        jLabel5.setText("Produit : ");

        jLabel2.setText("Mon premier programme en interface graphique");

        jLabel8.setFont(new java.awt.Font("TI-Nspire Sans", 3, 11)); // NOI18N
        jLabel8.setForeground(java.awt.Color.gray);
        jLabel8.setText("@avimimoun");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        buttonDonate.setText("Donate");
        buttonDonate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonDonateMouseClicked(evt);
            }
        });
        buttonDonate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDonateActionPerformed(evt);
            }
        });
        jMenu2.add(buttonDonate);

        About.setText("About");
        jMenu2.add(About);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(lbl1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(92, 92, 92))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)))
                        .addComponent(cmd2)
                        .addGap(34, 34, 34))))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmd1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cmd2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmd1)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmd1ActionPerformed

    private void cmd1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmd1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cmd1MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void cmd2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmd2MouseClicked
        // TODO add your handling code here:
        boolean TQ = true;
        while(TQ==true){
            String texte = jComboBox1.getSelectedItem().toString();
            if (texte=="Ajouter produit" || texte=="Rechercher produit" || texte=="Modifier produit"){
                new UPDATE(texte);
            }
            if (texte=="Lister produit"){
                ArrayList<Produit> lesProds = null;
                Produit leProd;
                ouvertureJframe(listerFrame, texte, 400, 500, true, true);
                listerText.setVisible(true);
                listerText.setEnabled(false);
                try {
                    lesProds = PasserelleBdd.lireProd();
                } catch (SQLException ex) {
                    Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
                }
                int i = 0;
                while (i<lesProds.size())
                {
                    leProd=lesProds.get(i); 
                    listerText.setText(listerText.getText()+"Identifiant : "+String.valueOf(leProd.getId())+"\nLibelle : "+leProd.getLib()+"\nPrix : "+String.valueOf(leProd.getPrix())+"\nStock : "+String.valueOf(leProd.getStock())+"\n\n");
                    i = i + 1;
                }
            }
            if (texte=="Supprimer produit"){
                ouvertureJframe(supprimerFrame, texte, 500, 110, true, true);
            }
            if (texte == "Prix max") {
                msgErreur.setSize(300,150);
                msgErreur.setVisible(true);
                float prix_max;
                prix_max = 0;
                try {
                    prix_max = PasserelleBdd.rechercherPxMax();
                } catch (SQLException ex) {
                    Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
                }
                jTextField2.setDisabledTextColor(Color.green);
                jTextField2.setText("Le prix max est : "+String.valueOf(prix_max));
                jTextField2.setVisible(true);
                jTextField2.setEnabled(false);
            }
            if (texte == "Valeur stock") {
                msgErreur.setSize(300,150);
                msgErreur.setVisible(true);
                float valStock = 0;
                ArrayList<Produit> lesProds = null;
                try {
                    lesProds = PasserelleBdd.lireProd();
                } catch (SQLException ex) {
                    Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
                }
                int i=0;
                while (i<lesProds.size())
                {
                        valStock += lesProds.get(i).getPrix() * lesProds.get(i).getStock();
                        i = i + 1;
                }
                jTextField2.setDisabledTextColor(Color.green);
                jTextField2.setText("La valeur du stock est : "+String.valueOf(valStock));
                jTextField2.setVisible(true);
                jTextField2.setEnabled(false);
            }
            if (texte == "Ajouter client"){
                ouvertureJframe(ajouterClient, texte, 500, 600, true, true);
            }
            if (texte == "Lister client"){
                ArrayList<Client> lesClients = null;
                Client unClient;
                ouvertureJframe(listerFrame, texte, 400, 500, true, false);
                listerText.setVisible(true);
                listerText.setEnabled(false);
                try {
                    lesClients = PasserelleBdd.lireCli();
                } catch (SQLException ex) {
                    Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
                }
                int i = 0;
                while (i<lesClients.size())
                {
                        unClient=lesClients.get(i); 
                        listerText.setText(listerText.getText()+"Identifiant : "+String.valueOf(unClient.getId())+"\nNom : "+unClient.getNom()+"\nAge : "+String.valueOf(unClient.getAge())+"\n\n");
                        i = i + 1;
                }
            }
            if (texte == "Ajouter commande"){
                ouvertureJframe(ajouterCommande, texte, 500, 300, true, true);
            }
            TQ = false;
        }

    }//GEN-LAST:event_cmd2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        listerFrame.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        supprimerFrame.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        // Cas supprimer un produit
        int unId = Integer.parseInt(jTextField1.getText());
        Produit leProd;
        int i = 0;
        try {
            leProd = PasserelleBdd.rechercherProd(unId);
            i = PasserelleBdd.modifProd('S', leProd);
        } catch (SQLException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (i==0)
        {
            jTextField2.setDisabledTextColor(Color.red);
            jTextField2.setText("Erreur lors de la supresssion du produit");
        }
        else
        {
            jTextField2.setDisabledTextColor(Color.green);
            jTextField2.setText("Le produit a bien etait supprime.");
        }
        msgErreur.setSize(300, 120);
        msgErreur.setVisible(true);
        jTextField2.setVisible(true);
        jTextField2.setEnabled(false);
                
    }//GEN-LAST:event_jButton3MouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        if(jTextField1.getDisabledTextColor()==Color.green){
            msgErreur.dispose();
            supprimerFrame.dispose();
        }
        else {
            msgErreur.dispose();
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        ajouterClient.dispose();
    }//GEN-LAST:event_jButton7MouseClicked

    private void suivantAddCli1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suivantAddCli1MouseClicked
        // TODO add your handling code here:
        int unId = Integer.parseInt(txtId1.getText());
        int unAge = Integer.parseInt(txtAge1.getText());
        String unNom = txtNom1.getText();
        
        Client C;
        C = new Client(unId, unNom, unAge);
        int i = 3;
        try {
            i = PasserelleBdd.modifCli('A', C);
        } catch (SQLException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
        switch (i) {
            case 0:
                jTextField2.setDisabledTextColor(Color.red);
                jTextField2.setText("Erreur lors de l'ajout du client");
                break;
            case 1:
                jTextField2.setDisabledTextColor(Color.green);
                jTextField2.setText("Le client a bien etait ajouté.");
                break;
            case 3:
                jTextField2.setDisabledTextColor(Color.red);
                jTextField2.setText("Erreur inconnue. Réessayer ulterieurement.");
                break;
            default:
                break;
        }
        msgErreur.setSize(300, 120);
        msgErreur.setVisible(true);
        jTextField2.setVisible(true);
        jTextField2.setEnabled(false);
    }//GEN-LAST:event_suivantAddCli1MouseClicked

    private void txtId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId1ActionPerformed

    private void txtNom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNom1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNom1ActionPerformed

    private void txtAge1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAge1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAge1ActionPerformed

    private void buttonDonateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDonateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDonateActionPerformed

    private void buttonDonateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDonateMouseClicked
        // TODO add your handling code here:
        ouvertureJframe(donateFrame, "Donate for Gestion_Produit", 300, 120, true, true);
        
    }//GEN-LAST:event_buttonDonateMouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton8MouseClicked

    private void idClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idClientActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        
        /*
            Faire un <custom code> sur les libelles de la JFrame Ajouter une commande
            Il faut que la premiere fois on affiche le 3. du cas d'utilisation
            La deuxieme fois il affiche le 5. du cas d'utilisation
        */
    }//GEN-LAST:event_jButton6MouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem About;
    private javax.swing.JFrame ajouterClient;
    private javax.swing.JFrame ajouterCommande;
    private javax.swing.JMenuItem buttonDonate;
    private javax.swing.JButton cmd1;
    private javax.swing.JButton cmd2;
    private javax.swing.JTextField date;
    private javax.swing.JFrame donateFrame;
    private javax.swing.JTextField idClient;
    private javax.swing.JTextField idCommande;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lab3;
    private javax.swing.JLabel lab4;
    private javax.swing.JLabel labAge1;
    private javax.swing.JLabel labId1;
    private javax.swing.JLabel labNom1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JFrame listerFrame;
    private javax.swing.JTextArea listerText;
    private javax.swing.JDialog msgErreur;
    private javax.swing.JButton suivantAddCli1;
    private javax.swing.JFrame supprimerFrame;
    private javax.swing.JTextField txtAge1;
    private javax.swing.JTextField txtId1;
    private javax.swing.JTextField txtNom1;
    // End of variables declaration//GEN-END:variables

    public String getTxtJComboBox1(){
        String texte = jComboBox1.getSelectedItem().toString();
        return texte;
    }
    
    /**
     *
     * @param uneFrame
     * @param unTexte
     */
    public void ouvertureJframe(JFrame uneFrame, String unTexte, int sizeA, int sizeB, boolean visible, boolean enable){
        uneFrame.setTitle(unTexte);
        uneFrame.setSize(sizeA, sizeB);
        uneFrame.setLocationRelativeTo(null);
        uneFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        uneFrame.setEnabled(enable);
        uneFrame.setVisible(visible);
    }
}
